import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {
  TooltipProvider,
} from "@/components/ui/tooltip"
import Navbar from "@/components/Navbar";
import Sidebar from "@/components/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TooltipProvider>
          <div className="flex min-h-screen w-full flex-col">
            <Sidebar />
            <Navbar />
            {children}
          </div>
        </TooltipProvider>
      </body>
    </html>
  );
}
